### PR TITLE
Add comments to functions for clarity (GH Copilot workspace generated)

### PR DESCRIPTION
**Pull request by insop**
Related to #5

This pull request adds comprehensive comments to the `lockdep` library, example program, and header file to improve code readability and maintainability.

- **lib/lockdep.c**: Adds detailed comments explaining the purpose and functionality of each function, including parameters, return values, and potential pitfalls. This includes functions for locking and unlocking the lockdep mutex, obtaining lock and thread IDs, initializing the lockdep system, and handling lock dependencies and deadlocks.
- **example/hello_mutex.c**: Introduces comments to the `taskA`, `taskB`, and `main` functions, explaining their roles in demonstrating mutex usage and potential deadlock scenarios. It also clarifies the logic behind the sequence of locking and unlocking mutexes.
- **include/lockdep.h**: Documents the functionality of `mutex_lock` and `mutex_unlock` functions, providing brief descriptions of their purpose and usage in preventing data races and ensuring exclusive access to resources.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/insop/lockdep/issues/5?shareId=c1e8d02a-591b-47c4-9d8d-e4f1dbf3dbea).

### CODE REVIEW

**Comment by insop** [comment]
@Junbo-Zheng 
PTAL

**Review by Junbo-Zheng — APPROVED** [review]
LGTM

**Comment by Junbo-Zheng** [comment]
@insop BTW, should we update the [readme.txt](https://github.com/insop/lockdep/blob/master/readme.txt) too?

**Comment by insop** [comment]
> @Junbo-Zheng
> PTAL

Good idea, PTAL https://github.com/insop/lockdep/pull/8

**Pull request merged**
